### PR TITLE
util: conditionally build CGO functions

### LINKED ISSUE #171: no buildable Go source files
Disclaimer: I'm not normally a Go developer, so some of my terms may not be quite right.

I'm trying to build a Docker plugin that use the `go-plugins-helpers` from Docker and I wanted the binary to run in Docker `alpine`, but `alpine` doesn't have the linked dynamic binaries or whatever, so I was reading up that I need to set `CGO_ENABLED=0` when building. I've tried a few different build commands, including:

```
CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags '-s' -o bin/linux/amd64/local-persist -v
CGO_ENABLED=0 go build -a -tags netgo -a -o bin/linux/amd64/local-persist -v
```

(Tried that last one with and without `CGO_ENABLED` flag. No error, but still won't run in `alpine`.)

I keep getting this error:

```
../github.com/docker/go-plugins-helpers/sdk/unix_listener.go:12:2: no buildable Go source files in /go/src/github.com/coreos/go-systemd/util
make: *** [binary-linux-amd64] Error 1
```

Steps to reproduce yourself:

```
git clone https://github.com/CWSpear/local-persist
cd local-persist
docker run -it -v `pwd`:/go/src/app  golang:onbuild bash
# now you'll be inside the docker container, next run:
export CGO_ENABLED=0
go get -v -d
go build [whatever flags] .
```

See https://github.com/docker/go-plugins-helpers/issues/50

### PR DESCRIPTION
**Pull request by heyitsanthony**
Some projects don't need the CGO functions in the util package;
split out the functions into a separate file so CGO_ENABLED=0
works if those functions are never used.

Fixes #171

### CODE REVIEW

**Comment by lucab** [comment]
This sounds good to me.

I'm just wondering if the non-cgo stub should still implement the functions that are being moved out here, just by erroring out. This would keep the same public interface, regardless of tags.

I'm not sure what is the idiomatic Go way here, @jonboulle?

**Comment by gyuho** [comment]
@lucab @jonboulle Can we get this merged?

go-systemd build in etcd is broken.

And I believe this is idiomatic, based on Go source tree.

```
$ find . -name '*_cgo_*'

./src/crypto/x509/root_cgo_darwin.go
./src/runtime/crash_cgo_test.go
```

And more

```
$ find . -name '*cgo_*'

./src/net/cgo_unix_test.go
./src/net/cgo_bsd.go
...
```

Thanks!

File: util/util.go [hunk 1]
```diff
@@ -18,190 +18,13 @@
...
-	// systemd >= 209 merged libsystemd-login into libsystemd proper
-	"libsystemd.so.0",
-	"libsystemd.so",
-}
-
-// GetRunningSlice attempts to retrieve the name of the systemd slice in which
-// the current process is running.
-// This function is a wrapper around the libsystemd C library; if it cannot be
-// opened, an error is returned.
-func GetRunningSlice() (slice string, err error) {
```
Comment (lucab) [inline util/util.go]: Function declaration and docstring should probably be retained, otherwise this part will be missing from godoc and we would get different public symbols depending on build tags. It can be simply implemented as a stub that always errors out. Same for the other functions moved out from this file.

**Comment by lucab** [comment]
I had another look at this, and I think that the current approach may be non-optimal: some public symbols will depend on build tags and will disappear from godoc (I guess, not sure).

Thus, I'd suggest a different way this could be done, by splitting current `util.go` into three parts:
 * `util.go` without any tag, only with the pure-Go functions (`GetMachineID` and `IsRunningSystemd`)
 * `util_cgo.go` gated behind a cgo tag, as you already did
 * `util_stub.go` gated behind a not-cgo tag, with stubs and docstring to match the cgo counterparts

**Comment by heyitsanthony** [comment]
@lucab all fixed up; I made the public functions call into private build-specific functions. It seemed weird to have the full godoc in `_stub.go` when the code there does nothing. Thanks!

File: util/util_stub.go [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+
+// +build !cgo
+
+package util
+
+import (
+	"fmt"
+)
+
+var errNoCGO = fmt.Errorf("go-systemd built with CGO disabled")
```
Comment (lucab) [inline util/util_stub.go]: This should be moved to `util.go` in order to let consumers error-match on this in all situations.

**Comment by lucab** [comment]
> I made the public functions call into private build-specific functions. It seemed weird to have the full godoc in _stub.go when the code there does nothing.

I agree this is even better than my half-botched proposal, thanks! Just one final remark inline, other than that it should be ok.

**Comment by heyitsanthony** [comment]
@lucab ok, ErrNoCGO exported

**Comment by lucab** [comment]
Great, LGTM!
